name: Package Firmware

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Archive firmware folder
        run: zip -r firmware.zip firmware/

      - name: Upload ZIP to Release
        uses: softprops/action-gh-release@v2
        with:
          files: firmware.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}